# Generated by Django 4.1.5 on 2023-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0005_option_correctanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmittedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_answers", models.TextField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name="correctanswer", old_name="Option", new_name="option",
        ),
    ]
