# Generated by Django 4.1.5 on 2023-01-17 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base_app", "0007_submittedanswer_submit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="participants",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
