# Generated by Django 4.1.5 on 2023-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0008_exam_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedanswer",
            name="correct_answers",
            field=models.PositiveBigIntegerField(max_length=100, null=True),
        ),
    ]
