# Generated by Django 4.1.5 on 2023-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0009_submittedanswer_correct_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submittedanswer",
            name="correct_answers",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
