# Generated by Django 4.1.5 on 2023-01-17 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base_app", "0012_alter_exam_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="participants",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
